  const kana = [{name: 'a', hiragana: 'あ', katakana: 'ア'}, 
                {name: 'i', hiragana: 'い', katakana: 'イ'},　
                {name: 'u', hiragana: 'う', katakana: 'ウ'},　
                {name: 'e', hiragana: 'え', katakana: 'エ'}, 
                {name: 'o', hiragana: 'お', katakana: 'オ'}, 
                {name: 'ka', hiragana: 'か', katakana: 'カ'}, 
                {name: 'ki', hiragana: 'き', katakana: 'キ'},　
                {name: 'ku', hiragana: 'く', katakana: 'ク'},　
                {name: 'ke', hiragana: 'け', katakana: 'ケ'}, 
                {name: 'ko', hiragana: 'こ', katakana: 'コ'},
                {name: 'ha', hiragana: 'は', katakana: 'ハ'}, 
                {name: 'hi', hiragana: 'ひ', katakana: 'ヒ'},　
                {name: 'hu', hiragana: 'ふ', katakana: 'フ'},　
                {name: 'he', hiragana: 'へ', katakana: 'ヘ'}, 
                {name: 'ho', hiragana: 'ほ', katakana: 'ホ'},
                {name: 'ma', hiragana: 'ま', katakana: 'マ'},  
                {name: 'mi', hiragana: 'み', katakana: 'ミ'}, 
                {name: 'mu', hiragana: 'む', katakana: 'ム'},　
                {name: 'me', hiragana: 'め', katakana: 'メ'},　
                {name: 'mo', hiragana: 'も', katakana: 'モ'}, 
                {name: 'sa', hiragana: 'さ', katakana: 'サ'},
                {name: 'shi', hiragana: 'し', katakana: 'シ'}, 
                {name: 'su', hiragana: 'す', katakana: 'ス'},　
                {name: 'se', hiragana: 'せ', katakana: 'セ'},　
                {name: 'so', hiragana: 'そ', katakana: 'ソ'}, 
                {name: 'ya', hiragana: 'や', katakana: 'ヤ'}, 
                {name: 'yu', hiragana: 'ゆ', katakana: 'ユ'}, 
                {name: 'yo', hiragana: 'よ', katakana: 'ヨ'},　
                {name: 'ta', hiragana: 'た', katakana: 'タ'},　
                {name: 'chi', hiragana: 'ち', katakana: 'チ'}, 
                {name: 'tsu', hiragana: 'つ', katakana: 'ツ'},
                {name: 'te', hiragana: 'て', katakana: 'テ'}, 
                {name: 'to', hiragana: 'と', katakana: 'ト'},　
                {name: 'ra', hiragana: 'ら', katakana: 'ラ'},　
                {name: 'ri', hiragana: 'り', katakana: 'リ'}, 
                {name: 'ru', hiragana: 'る', katakana: 'ル'}, 
                {name: 're', hiragana: 'れ', katakana: 'レ'}, 
                {name: 'ro', hiragana: 'ろ', katakana: 'ロ'},　
                {name: 'na', hiragana: 'な', katakana: 'ナ'},　
                {name: 'ni', hiragana: 'に', katakana: 'ニ'}, 
                {name: 'nu', hiragana: 'ぬ', katakana: 'ヌ'},
                {name: 'ne', hiragana: 'ね', katakana: 'ネ'},　
                {name: 'no', hiragana: 'の', katakana: 'ノ'},　
                {name: 'wa', hiragana: 'わ', katakana: 'ワ'}, 
                {name: 'wo', hiragana: 'を', katakana: 'ヲ'},
                {name: 'n', hiragana: 'ん', katakana: 'ン'}];


  const dakuten = [{name: 'pa', hiragana: 'ぱ', katakana: 'パ'}, 
                   {name: 'ba', hiragana: 'ば', katakana: 'バ'},　
                   {name: 'da', hiragana: 'だ', katakana: 'ダ'},　
                   {name: 'za', hiragana: 'ざ', katakana: 'ザ'}, 
                   {name: 'ga', hiragana: 'が', katakana: 'ガ'}, 
                   {name: 'pi', hiragana: 'ぴ', katakana: 'ピ'}, 
                   {name: 'bi', hiragana: 'び', katakana: 'ビ'},　
                   {name: 'di', nameAlt: 'dzi', hiragana: 'ぢ', katakana: 'ヂ'},　
                   {name: 'ji', hiragana: 'じ', katakana: 'ジ'}, 
                   {name: 'gi', hiragana: 'ぎ', katakana: 'ギ'},
                   {name: 'pu', hiragana: 'ぷ', katakana: 'プ'}, 
                   {name: 'bu', hiragana: 'ぶ', katakana: 'ブ'},　
                   {name: 'du', nameAlt: 'dzu', hiragana: 'づ', katakana: 'ヅ'},　
                   {name: 'zu', hiragana: 'ず', katakana: 'ズ'}, 
                   {name: 'gu', hiragana: 'ぐ', katakana: 'グ'},
                   {name: 'pe', hiragana: 'ぺ', katakana: 'ペ'},  
                   {name: 'be', hiragana: 'べ', katakana: 'ベ'}, 
                   {name: 'de', hiragana: 'で', katakana: 'デ'},　
                   {name: 'ze', hiragana: 'ぜ', katakana: 'ゼ'},　
                   {name: 'ge', hiragana: 'げ', katakana: 'ゲ'}, 
                   {name: 'po', hiragana: 'ぽ', katakana: 'ポ'},
                   {name: 'bo', hiragana: 'ぼ', katakana: 'ボ'}, 
                   {name: 'do', hiragana: 'ど', katakana: 'ド'},　
                   {name: 'zo', hiragana: 'ぞ', katakana: 'ゾ'},　
                   {name: 'go', hiragana: 'ご', katakana: 'ゴ'},];


  const combo = [{name: 'nya', hiragana: 'にゃ', katakana: 'ニャ'}, 
                   {name: 'cha', hiragana: 'ちゃ', katakana: 'チャ'},　
                   {name: 'sha', hiragana: 'しゃ', katakana: 'シャ'},　
                   {name: 'kya', hiragana: 'きゃ', katakana: 'キャ'}, 
                   {name: 'nyu', hiragana: 'にゅ', katakana: 'ニュ'}, 
                   {name: 'chu', hiragana: 'ちゅ', katakana: 'チュ'}, 
                   {name: 'shu', hiragana: 'しゅ', katakana: 'シュ'},　
                   {name: 'kyu', hiragana: 'きゅ', katakana: 'キュ'},　
                   {name: 'nyo', hiragana: 'にょ', katakana: 'ニョ'}, 
                   {name: 'cho', hiragana: 'ちょ', katakana: 'チョ'},
                   {name: 'sho', hiragana: 'しょ', katakana: 'ショ'}, 
                   {name: 'kyo', hiragana: 'きょ', katakana: 'キョ'},　
                   {name: 'gya', hiragana: 'ぎゃ', katakana: 'ギャ'},　
                   {name: 'rya', hiragana: 'りゃ', katakana: 'リャ'}, 
                   {name: 'mya', hiragana: 'みゃ', katakana: 'ミャ'},
                   {name: 'hya', hiragana: 'ひゃ', katakana: 'ヒャ'},
                   {name: 'gyu', hiragana: 'ぎゅ', katakana: 'ギュ'},  
                   {name: 'ryu', hiragana: 'りゅ', katakana: 'リュ'}, 
                   {name: 'myu', hiragana: 'みゅ', katakana: 'ミュ'},　
                   {name: 'hyu', hiragana: 'ひゅ', katakana: 'ヒュ'},　
                   {name: 'gyo', hiragana: 'ぎょ', katakana: 'ギョ'}, 
                   {name: 'ryo', hiragana: 'りょ', katakana: 'リョ'},
                   {name: 'myo', hiragana: 'みょ', katakana: 'ミョ'}, 
                   {name: 'hyo', hiragana: 'ひょ', katakana: 'ヒョ'},　
                   {name: 'pya', hiragana: 'ぴゃ', katakana: 'ピャ'},　
                   {name: 'bya', hiragana: 'びゃ', katakana: 'ビャ'},
                   {name: 'dya', nameAlt: 'dzya', hiragana: 'ぢゃ', katakana: 'ヂャ'},
                   {name: 'jya', hiragana: 'じゃ', katakana: 'ジャ'},  
                   {name: 'pyu', hiragana: 'ぴゅ', katakana: 'ピュ'}, 
                   {name: 'byu', hiragana: 'びゅ', katakana: 'ビュ'},　
                   {name: 'dyu', nameAlt: 'dzyu', hiragana: 'ぢゅ', katakana: 'ヂュ'},　
                   {name: 'jyu', hiragana: 'じゅ', katakana: 'ジュ'}, 
                   {name: 'pyo', hiragana: 'ぴょ', katakana: 'ピョ'},
                   {name: 'byo', hiragana: 'びょ', katakana: 'ビョ'},
                   {name: 'dyo', nameAlt: 'dzyo', hiragana: 'ぢょ', katakana: 'ヂョ'}, 
                   {name: 'jyo', hiragana: 'じょ', katakana: 'ジョ'},];



  export {kana, dakuten, combo}